spring.application.name=fintech-auth-backend

spring.mongodb.uri=${MONGODB_CONNECTION_STRING}

jwt.secret=${JWT_SECRET_KEY}
#1 day in millis
jwt.access.expiration=86400000
#2 days in millis
jwt.refresh.expiration=172800000

resend.api.key=${RESEND_API_KEY}
resend.from.email=${RESEND_FROM_EMAIL}

spring.data.redis.url=${REDIS_CONNECTION_STRING}
spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=50
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=5
spring.data.redis.lettuce.pool.max-wait=2000ms

logging.level.org.springframework.security=DEBUG
