spring.application.name=fintech-auth-backend

spring.mongodb.uri=${MONGODB_CONNECTION_STRING}

jwt.secret=${JWT_SECRET_KEY}

#1 day in millis
jwt.access.expiration=86400000

#2 days in millis
jwt.refresh.expiration=172800000

spring.data.redis.url=${REDIS_CONNECTION_STRING}
spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=50
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=5
spring.data.redis.lettuce.pool.max-wait=2000ms

logging.level.org.springframework.security=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.ssl.enable=true
#spring.mail.properties.mail.debug=true
